[package]
name = "wot_replay_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wot_replay_parser = "0.2.2"
serde_json = "1.0"